### PR TITLE
New Module: ManhwaPool

### PR DESCRIPTION
**Pull request by 10lalib**
ManhwaPool Module

### CODE REVIEW

**Comment by 10lalib** [comment]
Hello
I made a mistake when copying the correct module. I have fixed it now.
please review it
Thank you

**Comment by Slasar41** [comment]
Still not like this.
Delete your `madara.lua` file and then edit the existing `Madara.lua` file.

**Comment by 10lalib** [comment]
Thank you for guiding me on this i am still new to github so it was my first contribution

I edit the Madara.lua as you mentioned the deleted the madara.lua file that i had made

**Comment by Slasar41** [comment]
Nice, thanks for the contribution!

**Pull request merged**
