### PR TITLE
Update Indonesian language

### PR DESCRIPTION
**Pull request by Slasar41**

### CODE REVIEW

**Comment by Slasar41** [comment]
I just noticed a few words from old FMD getting removed, it caused the translation became not completed. Like from lines 2322 until the end. https://www.diffchecker.com/Uz3Y6MrI
Why?

**Comment by Tmp341** [comment]
What removed from where?

**Comment by Slasar41** [comment]
FMD from riderkick version.
In that link, I compare the English language in this version with FMD from riderkick version.

**Comment by Tmp341** [comment]
This is the commit you're looking for : 

d2fff2d

**Comment by SDXC** [comment]
@Slasar41 In my first release I used the automatically updated PO files. Problem is, the automatic addition/removal of new elements doesn't take the lua scripts into consideration.

For the latest release I added the old files from the releases and will only use and update these.

The files you see currently in this repo are only the automatically generated files. The releases contain the correct files only for now. I will restructure the repo at some point.

**Comment by Slasar41** [comment]
So you will put back the missing lines?
If the language set to English, the missing lines still properly displays as English words.
But if I set to Indonesian or other language, it became broken like this
image

**Comment by AbidZakaria** [comment]
@Slasar41 you using old FMD, please update your FMD

**Comment by Slasar41** [comment]
@AbidZakaria I use version 0.9.161.0

**Comment by SDXC** [comment]
ignore all the old commits. I have moved the correct language files in a dedicated folder and removed the generic ones completely out of the repo.

@Slasar41 Your changes that you commited will be re-merged soon as well.

**Comment by Slasar41** [comment]
Nice, thanks.

**Comment by SDXC** [comment]
done

**Pull request merged**
