### PR TITLE
Add ManhuaPlus and Martial Scans

### LINKED ISSUE #1020: Martial Scans now works perfectly fine now
Previously adding this code simply not enouge for this site but now _it just works_. 
Just add this code in Madara.lua it will good to go.

  AddWebsiteModule('MartialScans', 'https://martialscans.com', cat)

Please add it to official support. Thank you

Capture

### PR DESCRIPTION
**Pull request by Tmp341**
Closes #1020 

* Add Martial Scans
* Add ManhuaPlus

### CODE REVIEW

**Comment by SDXC** [comment]
@Tmp341 In cases for new websites where you only have to add the url or a copy from a template and you have tested it, you don't need to wait for our approval. No harm will be done in that case. Only when changing code that also could affect other websites an approval would be needed.

**Comment by Tmp341** [comment]
> 
> 
> @Tmp341 In cases for new websites where you only have to add the url or a copy from a template and you have tested it, you don't need to wait for our approval. No harm will be done in that case. Only when changing code that also could affect other websites an approval would be needed.

It is not my code, so i don't know what it contains. That's why i put a review request.

**Comment by Tmp341** [comment]
I dunno how to do that :D

**Comment by Slasar41** [comment]
Delete ManhuaPlus.lua.
Edit TruyenChon.lua file, put `AddWebsiteModule('ManhuaPlus', 'https://manhuaplus.com', cat)` on English category and replace the getpagenumber function like in my comment before.
The website doesn't have manga directory so we should leave it for now.

**Comment by Tmp341** [comment]
I've made the change, i think.

**Pull request merged**
