### PR TITLE
Indonesian websites: Fixed all and add site [KOMIKAV]

### PR DESCRIPTION
**Pull request by Slasar41**
Issues https://github.com/fmd-project-team/FMD/issues/322, https://github.com/fmd-project-team/FMD/issues/331, and https://github.com/fmd-project-team/FMD/issues/332
Helping @AbidZakaria

### CODE REVIEW

**Comment by SDXC** [comment]
I'll be able to check these on friday.

**Comment by Slasar41** [comment]
Request https://github.com/fmd-project-team/FMD/issues/358

**Comment by AbidZakaria** [comment]
@Slasar41 maybe title site KomiKav

**Comment by Slasar41** [comment]
Hmm, in the website's title it's full caps though.
IMG_20190719_114356

**Comment by Tmp341** [comment]
It should be ``KomikAV`` or ``KomikAv``. Or leave it ``Komikav`` etc.

**Comment by Slasar41** [comment]
Alright, let @SDXC to rename it later.

**Pull request merged**
